name: Notificar no Discord

on:
  push:
    branches:
      - '**'  # qualquer branch

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem no Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          AUTHOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
          MESSAGE: ${{ github.event.head_commit.message }}
          URL: ${{ github.event.head_commit.url }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"**Novo commit**
            🌿 Branch: \`${BRANCH}\`
            👤 Autor: \`${AUTHOR}\`
            📦 Projeto: \`${REPO}\`
            💬 Commit: ${MESSAGE}
            [Ver commit](${URL})\"
                        }" \
                        $DISCORD_WEBHOOK
