name: "Notificar no Discord - Front-End"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]


jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se o webhook está setado
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "⚠️ DISCORD_WEBHOOK está vazio"
            exit 1
          else
            echo "✅ DISCORD_WEBHOOK está configurado"
          fi

     - name: Enviar notificação para o Discord (Front-End)
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  run: |
    EVENT="${{ github.event_name }}"
    AUTHOR="${{ github.actor }}"
    REPO="${{ github.repository }}"
    BRANCH="${{ github.ref_name }}"
    URL=""
    MSG=""
    TITLE=""
    DATA_HORA=$(TZ=America/Sao_Paulo date "+%a %d %b %Y %T %Z")

    if [ "$EVENT" = "push" ]; then
      TITLE="Novo commit"
      MSG="**$AUTHOR** enviou um novo commit para o repositório **$REPO**.\n\n💬 **Mensagem do commit:**\n${{ github.event.head_commit.message }}"
      URL="${{ github.server_url }}/${REPO}/commit/${{ github.sha }}"
    elif [ "$EVENT" = "pull_request" ]; then
      ACTION="${{ github.event.action }}"
      TITLE="Pull Request: $ACTION"
      MSG="**$AUTHOR** fez um *pull request* em **$REPO** com ação **$ACTION**.\n🔗 [Ver PR](${{ github.event.pull_request.html_url }})"
      URL="${{ github.event.pull_request.html_url }}"
    fi

    curl -H "Content-Type: application/json" \
      -X POST \
      -d "{
        \"embeds\": [{
          \"title\": \"$TITLE\",
          \"description\": \"$MSG\",
          \"color\": 3447003,
          \"fields\": [
            {\"name\": \"🔗 Link\", \"value\": \"$URL\"},
            {\"name\": \"📦 Branch\", \"value\": \"$BRANCH\", \"inline\": true},
            {\"name\": \"🕒 Horário\", \"value\": \"$DATA_HORA\", \"inline\": true}
          ]
        }]
      }" \
      "$DISCORD_WEBHOOK"


